server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: web-demo
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.leecode.webdemo: INFO
    org.springframework.web: INFO
